db.url=jdbc:postgresql://postgres-users:5432/users
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver

hibernate.default_schema=user_service
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=mySecretKeyForJwtTokenGenerationInMarketplaceApplication2026
jwt.expiration=86400000

liquibase.changeLog=classpath:db/changelog-master.xml

ad.service.url=http://ad-service:8080/internal/ads/