db.url=jdbc:postgresql://postgres:5432/bank
db.username=bank
db.password=bank

kafka.bootstrap-servers=kafka1:9092,kafka2:9092,kafka3:9092
app.kafka.topic=bank.transfers
app.kafka.group-id=bank-consumers
app.producer.delay-ms=200